Use cabal new-build on travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,61 +1,135 @@
-# This file has been generated by travis-meta-yaml 0.2.0.0
-# see https://github.com/phadej/travis-meta-yaml
-sudo: false
+# This Travis job script has been generated by a script via
+#
+#   runghc make_travis_yml_2.hs '--irc-channel' 'irc.freenode.org#clash-lang' 'clash-prelude.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
 language: c
-before_install:
-- ghdl --version
-- chmod +x ./.travis/install_iverilog.sh
-- ./.travis/install_iverilog.sh
-- export PATH=$PATH:$HOME/iverilog/bin
-- vvp -V
-- export PATH=/opt/ghc/$GHCVER/bin:$PATH
-- if [ -n "$CABALVER" ]; then export PATH=/opt/cabal/$CABALVER/bin:$PATH; fi
-- export PATH=~/.local/bin:$PATH
-- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L
-  https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1
-  -C ~/.local/bin '*/stack'; fi
-- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
-  '?')]"
-- stack +RTS -N2 -RTS --version
-install:
-- if [ "$STACK_SOLVER" = "YES" ]; then rm -f stack.yaml; stack update; stack init
-  --solver; fi; stack --no-terminal --skip-ghc-check list-dependencies|sort > installplan.txt;
-  cat installplan.txt; stack --no-terminal --skip-ghc-check setup; if diff -u $HOME/.stack-work-cache/installplan.txt
-  installplan.txt; then echo "cabal build-cache HIT"; rm -rf .stack-work; cp -a $HOME/.stack-work-cache
-  .stack-work; rm -f .stack-work/installplan.txt; else echo "cabal build-cache MISS";
-  rm -rf $HOME/.stack-work-cache; stack --no-terminal --skip-ghc-check build
-  --only-dependencies; fi; if [ ! -d $HOME/.stack-work-cache ]; then echo "snapshotting
-  package-db to build-cache"; cp -a .stack-work $HOME/.stack-work-cache; cp -a installplan.txt
-  $HOME/.stack-work-cache/installplan.txt; fi;
-script:
-- if [ "$PEDANTIC" = "YES" ]; then export STACKOPTS=--pedantic; fi
-- stack --no-terminal --skip-ghc-check build --haddock --no-haddock-deps $STACKOPTS
-# - stack --no-terminal --skip-ghc-check sdist
-- stack exec clash-testsuite
-matrix:
-  fast_finish: true
-  include:
-  - env: GHCVER=8.2.1 STACKOPTS="--flag clash-testsuite:travisci"
-    addons:
-      apt:
-        sources:
-        - pgavin-ghdl
-        packages:
-        - libgmp-dev
-        - ghdl
-        - gperf
-    compiler: ! ': # ghc-8.2.1'
-cache:
-  directories:
-  - ~/.stack
-  - ~/.local
-  - ~/.stack-work-cache
-  - $HOME/iverilog
-  apt: true
+sudo: false
+
+git:
+  submodules: true  # whether to recursively clone submodules
+
 notifications:
   irc:
-    skip_join: true
     channels:
-    - "irc.freenode.org#clash-lang"
+      - "irc.freenode.org#clash-lang"
+    skip_join: true
     template:
-    - "\x0313clash-compiler\x0F/\x0306%{branch}\x0F \x0314%{commit}\x0F %{message}\x0302\x1F%{build_url}\x0F"
+      - "\x0313clash-prelude\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+    - $HOME/iverilog
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -rfv $HOME/.cabal/packages/head.hackage
+
+matrix:
+  include:
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.2,ghdl,gperf], sources: [hvr-ghc,pgavin-ghdl]}}
+    - compiler: "ghc-8.4.1"
+      env: GHCHEAD=true
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.4.1,ghdl,gperf], sources: [hvr-ghc,pgavin-ghdl]}}
+
+  allow_failures:
+    - compiler: "ghc-8.4.1"
+
+before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
+  - ghdl --version
+  - chmod +x ./.travis/install_iverilog.sh
+  - ./.travis/install_iverilog.sh
+  - export PATH=$PATH:$HOME/iverilog/bin
+  - vvp -V
+
+install:
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - INSTALLED=${INSTALLED-true}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      sed -i.bak 's/-- allow-newer:.*/allow-newer: *:base, *:template-haskell, *:ghc, *:Cabal/' ${HOME}/.cabal/config
+
+      echo 'repository head.hackage'                                                        >> ${HOME}/.cabal/config
+      echo '   url: http://head.hackage.haskell.org/'                                       >> ${HOME}/.cabal/config
+      echo '   secure: True'                                                                >> ${HOME}/.cabal/config
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> ${HOME}/.cabal/config
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> ${HOME}/.cabal/config
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> ${HOME}/.cabal/config
+      echo '   key-threshold: 3'                                                            >> ${HOME}/.cabal.config
+
+      cabal new-update head.hackage -v
+    fi
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \"./*/*.cabal\"\\n' > cabal.project"
+  - cat cabal.project
+  - if [ -f "./configure.ac" ]; then
+      (cd "." && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf "."/.ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+  - SRCDIR=$PWD
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+  # test that source-distributions can be generated
+  - (cd "./clash-lib" && cabal sdist && cd "..")
+  - mv "."/clash-lib/dist/clash-lib-*.tar.gz ${DISTDIR}/
+  - (cd "./clash-ghc" && cabal sdist && cd "..")
+  - mv "."/clash-ghc/dist/clash-ghc-*.tar.gz ${DISTDIR}/
+  - find ${DISTDIR} -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' -C ${DISTDIR} \;
+  - "printf 'packages: %b/clash-lib-*/*.cabal %b/clash-ghc-*/*.cabal clash-prelude/*.cabal testsuite/*.cabal\\n' ${DISTDIR} ${DISTDIR} > cabal.project"
+  - cat cabal.project
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # Build with installed constraints for packages in global-db
+  - if $INSTALLED; then echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks $(${HCPKG} list --global --simple-output --names-only | sed 's/\([a-zA-Z0-9-]\{1,\}\) */--constraint="\1 installed" /g') all | sh; else echo "Not building with installed constraints"; fi
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-run -w ${HC} clash-testsuite; fi
+
+  # cabal check
+  - (cd ${DISTDIR}/clash-lib-* && cabal check)
+  - (cd ${DISTDIR}/clash-ghc-* && cabal check)
+
+  # haddock
+  - cd ${SRCDIR}
+  - rm -rf ./dist-newstyle
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+# REGENDATA ["--irc-channel","irc.freenode.org#clash-lang","clash-prelude.cabal"]
+# EOF
